version: '3.8'
services:
  dbtest:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dbtest
    hostname: dbtest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=.Carlosgrillet23
    volumes:
      - ./backup:/var/opt/mssql/backup
      - ./script/db_restore.sh:/db_restore.sh
